runtime: go
api_version: go1

handlers:
- url: /
  static_files: site/public/index.html
  upload: site/public/index.html
  secure: always

- url: /blog
  static_files: site/public/blog/index.html
  upload: site/public/blog/index.html
  secure: always

- url: /blog/(.*)/
  static_files: site/public/blog/\1/index.html
  upload: site/public/blog/(.*)/index.html
  secure: always

- url: /l/.*
  script: _go_app
  secure: always
# kept for backwards compatilibity
- url: /(\+|bio|gh|l|nil|pic|t)
  script: _go_app
  secure: always

- url: /
  static_dir: site/public/
  secure: always