application: campoy-personal
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: site/public/index.html
  upload: site/public/index.html
  secure: always
- url: /
  static_dir: site/public/
  secure: always
# - url: /l/.*
#   script: _go_app
#   secure: always
