application: campoy-personal
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /favicon.ico
  static_files: static/identicon.png
  upload: static/identicon.png
  secure: always
- url: /
  static_files: static/home.html
  upload: static/home.html
  secure: always
- url: /.*
  script: _go_app
  secure: always
