application: campoy-personal
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/img/identicon.png
  upload: static/img/identicon.png
- url: /
  static_files: static/home.html
  upload: static/home.html
- url: /.*
  script: _go_app
