baseURL = "https://www.campoy.cat/"
languageCode = "en-us"
title = "Francesc Campoy Flores"
theme = "introduction"

PygmentsCodeFences = true
PygmentsStyle = "monokai"


[permalinks]
fixed = ":title/"
blog  = "blog/:filename/"

[params]
author = "FrancescCampoy Flores"
email = "francesc@campoy.cat"
firstname = "Francesc"
tagline = "Software Engineer, Public Speaker, Good Guy"
avatar = "img/profile.jpg"
dateform = "Jan 2, 2006"
dateformfull = "Mon January 2 2006"
cachebuster = true
description = "Francesc's home page"
# faviconfile = "img/fav.ico"
highlightjs = true
lang = "en"
footertext = ""

# Social icons appear in introduction and contact section. Input your username only, eg "you" as it appears in "twitter.com/you"
linkedin      = "campoy/"
twitter       = "francesc"
github        = "campoy"
googleplus    = "FrancescCampoyFlores"
codepen       = ""
pinterest     = ""
facebook      = ""

showblog        = true # Show Blog section on home page
showallposts    = false # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
showlatest      = true # Show latest blog post summary
sharebuttons    = true # On post pages, show share this social buttons

showprojects    = true # Show Projects section on home page

# This is your projects section. Three images of the same dimensions will look the nicest. If images are omitted, text links will be shown.
project1link    = "https://youtube.com/c/justforfunc"
project1img     = "img/justforfunc.png"
project1title   = "justforfunc"
project1desc    = "Tune in on YouTube every two weeks to see me hacking with Go and Cloud technologies while cracking amazing jokes (imo)."

project2link    = "https://github.com/campoy/go-tooling-workshop"
project2img     = "img/go-tooling.png"
project2title   = "Go Tooling in Action"
project2desc    = "My most successful workshop to date: covering the tools all gophers use daily. Do you want it at your conference? Hit me up!"

project3link    = "https://github.com/campoy/embedmd"
project3img     = "img/embedmd.png"
project3title   = "embedmd"
project3desc    = "A simple tool that embeds code into your Markdown files from any other files, and keeps everything in sync."


